---
title: "Citations for OCS papers"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r, echo = FALSE, hide = TRUE, message = FALSE}
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
yaml <- yaml::read_yaml(file.path(root_dir, "_config_automation.yml"))

citations <- readr::read_tsv(file.path("metricminer_data", "citations", "citations.tsv"))

```

### Total citations per original paper describing OCS

```{r,echo=FALSE, message=FALSE}
library(dplyr)
# here we remove duplicates if there are any of the same titles of citing papers for each original paper and then get a count of the number of rows for each original paper (aka how many times it is cited)
knitr::kable(citations %>%
  distinct(original_paper, cite_titles, .keep_all = TRUE) %>%
  count(original_paper))
```

### Total citations across papers describing OCS

```{r echo=FALSE, results = 'asis'}
cat(unlist(citations %>% distinct(original_paper, cite_titles, .keep_all = TRUE) %>% count(original_paper)%>% dplyr::summarize(download_total = sum(n)), use.names = FALSE))
```
