---
title: "OCS Repos on GitHub"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
date: "`r format(Sys.time(), '%d %B, %Y')`"

---

```{r, echo = FALSE, hide = TRUE, message=FALSE, warning = FALSE}
library(ggplot2)
library(magrittr)

root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
yaml <- yaml::read_yaml(file.path(root_dir, "_config_automation.yml"))

## For github
github_overall <- readr::read_tsv(file.path("metricminer_data", "github", "github.tsv"))
github_timecourse <- readr::read_tsv(file.path("metricminer_data", "github", "github_timecourse.tsv"))
```
## Snapshot metrics

### Number of forks and stars

```{r eval = FALSE, echo=FALSE, hide=TRUE, message=FALSE, warning=FALSE, fig.width = 10.06, fig.height = 6.29}
github_overall %>%
     select(repo_name, num_forks, num_stars) %>%
     replace_na(list(num_forks = 0)) %>%
     pivot_longer(c("num_forks", "num_stars"), values_to = "metric_value", names_to = "which_metric") %>%
     mutate(repo = str_replace_all(repo_name, "opencasestudies/", ""),
            repo_type = case_when(str_detect(repo_name, "template") ~ "Template",
                                  str_detect(repo_name, "ocs-") ~ "Case Study",
                                  str_detect(repo_name, "_Guide") ~ "Guide"),
            which_metric = str_replace_all(which_metric, "num_", "")) %>%
     ggplot(aes(y = reorder(repo, metric_value), x = metric_value, fill=repo_type)) +
     facet_wrap(~which_metric) +
     geom_bar(stat = "identity") +
     theme_classic() +
     labs(fill = "") +
     xlab("") +
     ylab("opencasestudies organization repository") +
     geom_text(aes(label = metric_value, group = repo),
               hjust = -0.5, size=3)
```

### Number of contributors:

```{r eval = FALSE, echo = FALSE, hide = TRUE, message=FALSE, warning = FALSE, fig.width = 9.22, fig.height = 6.29}
github_overall %>%
  mutate(repo = str_replace_all(repo_name, "opencasestudies/", ""),
         repo_type = case_when(str_detect(repo_name, "template") ~ "Template",
                              str_detect(repo_name, "ocs-") ~ "Case Study",
                              str_detect(repo_name, "_Guide") ~ "Guide")) %>%
  ggplot(aes(y = reorder(repo, num_contributors), x = num_contributors, fill=repo_type)) +
  geom_bar(stat = "identity") +
  theme_classic() +
  labs(fill = "") +
  xlab("Number of Contributors") +
  ylab("opencasestudies organization repository") +
  geom_text(aes(label = num_contributors, group = repo),
                  hjust = -0.5, size=3)
```

<!---
## Timecourse metrics

### Unique views over time

```{r echo = FALSE, hide = TRUE, message=FALSE, warning=FALSE, fig.width = 12.40, fig.height = 6.20}
github_timecourse %>%
    mutate(repo = str_replace_all(repo, "opencasestudies/", ""),
           repo_type = case_when(str_detect(repo, "template") ~ "Template",
                                 str_detect(repo, "ocs-") ~ "Case Study",
                                 str_detect(repo, "_Guide") ~ "Guide")) %>%
    ggplot(aes(x = timestamp, y = uniques_views, fill = repo_type, color = repo_type)) +
    facet_wrap(~repo) +
    geom_line(stat = "identity") +
    theme_classic() +
    ylab("Unique views") +
    xlab("Date") + theme(axis.text.x = element_text(angle = 60, hjust = 1, vjust = 1))
```

### Unique clones over time

```{r echo=FALSE, hide=TRUE, message=FALSE, warning=FALSE, fig.width = 12.40, fig.height = 6.20}
github_timecourse %>%
    mutate(repo = str_replace_all(repo, "opencasestudies/", ""),
           repo_type = case_when(str_detect(repo, "template") ~ "Template",
                                 str_detect(repo, "ocs-") ~ "Case Study",
                                 str_detect(repo, "_Guide") ~ "Guide")) %>%
    ggplot(aes(x = timestamp, y = uniques_clones, fill = repo_type, color = repo_type)) +
    facet_wrap(~repo) +
    geom_line(stat = "identity") +
    theme_classic() +
    ylab("Unique clones") +
    xlab("Date") + theme(axis.text.x = element_text(angle = 60, hjust = 1, vjust = 1))
```
-->
