---
title: "Google Analytics"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r, echo = FALSE, hide = TRUE, message = FALSE}
library(lubridate)

root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
yaml <- yaml::read_yaml(file.path(root_dir, "_config_automation.yml"))

## For google analytics
ga_metrics <- readr::read_tsv(file.path("metricminer_data", "ga", "ga_metrics.tsv"))
ga_metric_streams <- readr::read_csv(file.path("metricminer_data", "manual", "ga_report_csv_export.csv"))
ga_dimensions <- readr::read_tsv(file.path("metricminer_data", "ga", "ga_dimensions.tsv"))
ga_link_clicks <- readr::read_tsv(file.path("metricminer_data", "ga", "ga_link_clicks.tsv"))
```

## Engagement statistics

### Case study specific

```{r echo = FALSE, hide = TRUE, message=FALSE, warning = FALSE}
ga_metric_streams %>% 
  filter(str_detect(`Page path and screen class`, "ocs-bp")) %>% 
  filter(!str_detect(`Page path and screen class`, "interactive|html|templates")) %>% 
  select(c(`Page path and screen class`, Views, `Active users`, `Average engagement time per active user`, `Event count`)) %>% 
  pivot_longer(!c(`Page path and screen class`), values_to = "value", names_to = "metric_name") %>%
  ggplot(aes(x = reorder(`Page path and screen class`, value), y = value)) +
  geom_bar(position = "dodge", stat = "identity") +
  theme_minimal() +
  facet_wrap(~metric_name, scales = "free_y") + 
  theme(axis.text.x=element_text(angle=60, hjust=1), 
                 strip.text.x = element_text(size = 8)) +
  xlab("Case study") +
  ylab("")
```

### Main Webpage and Pooled Across Case Studies

```{r echo=FALSE, hide=TRUE, message=FALSE, warning=FALSE}
knitr::kable(ga_metrics)
```

## Web traffic overtime

### Main Open Case Studies Website

```{r echo=FALSE, hide=TRUE, message=FALSE, warning=FALSE, fig.height = 8.89, fig.width = 6.20}
ga_dimensions %>% 
  filter(str_detect(website, "OCS main")) %>%
  filter(!str_detect(fullPageUrl, "/?q=|localhost|.com|rmd_output")) %>%
  mutate(month_year = ym(paste0(year, "-", month))) %>%
  group_by(month_year) %>% 
  count() %>% 
  ggplot(ggplot2::aes(y = n, x = month_year)) + 
  geom_bar(stat = "identity") + 
  scale_x_date(date_labels = "%b %Y") + 
  ylab("OCS Main Website Traffic") +
  xlab("") +
  theme_minimal() +
  theme(axis.text.x=element_text(angle=60, hjust=1))
```

### Case Studies

```{r echo=FALSE, hide=TRUE, message=FALSE, warning=FALSE, fig.height = 8.89, fig.width = 6.20}
ga_dimensions %>%
  filter(!str_detect(website, "OCS main")) %>%
  filter(str_detect(fullPageUrl, "ocs-bp")) %>%
  filter(!str_detect(fullPageUrl, "rsconnect|interactive")) %>%
  mutate(month_year = ym(paste0(year, "-", month)),
    case_study = case_when(str_detect(fullPageUrl, "youth-mental-health") ~ "ocs-bp-youth-mental-health",
                                str_detect(fullPageUrl, "opioid") ~ "ocs-bp-opioid-rural-urban",
                                str_detect(fullPageUrl, "obesity") ~ "ocs-bp-rural-and-urban-obesity",
                                str_detect(fullPageUrl, "vaping") ~ "ocs-bp-vaping-case-study",
                                str_detect(fullPageUrl, "school-shootings") ~ "ocs-bp-school-shootings-dashboard",
                                str_detect(fullPageUrl, "diet") ~ "ocs-bp-diet",
                                str_detect(fullPageUrl, "youth-disconnection") ~ "ocs-bp-youth-disconnection",
                                str_detect(fullPageUrl, "co2-emissions") ~ "ocs-bp-co2-emissions",
                                str_detect(fullPageUrl, "RTC-wrangling") ~ "ocs-bp-RTC-wrangling",
                                str_detect(fullPageUrl, "RTC-analysis") ~ "ocs-bp-RTC_analysis",
                                str_detect(fullPageUrl, "pollution") ~ "ocs-bp-air-pollution")) %>%
  group_by(month_year, case_study) %>% 
  count() %>% 
  ggplot(ggplot2::aes(y = n, x = month_year, fill=case_study)) + 
  geom_bar(stat = "identity") + 
  facet_wrap(~case_study) +
  scale_x_date(date_labels = "%b %Y") + 
  ylab("Case Study Website Traffic") +
  xlab("") +
  theme_minimal() +
  theme(axis.text.x=element_text(angle=60, hjust=1), legend.position = "none")
```


